<a href="https://colab.research.google.com/github/haribabuofficial/3-Pandas/blob/main/t3_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

## Series

### Creating Series

In [113]:
import pandas as pd

import numpy as np

data = np.array(["a", "b", "c", "d", "e"])

print(type(data))

ser = pd.Series(data)

print(ser)

print(type(ser))

<class 'numpy.ndarray'>
0    a
1    b
2    c
3    d
4    e
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
ser[4]

'e'

In [ ]:
import pandas as pd

list1 = ["a", "b", "c", "d", "e"]

ser = pd.Series(list1)

print(ser)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
import pandas as pd

calories = {"Jan": 420, "Feb": 380, "Mar": 390}

myvar = pd.Series(calories)

print(myvar)

Jan    420
Feb    380
Mar    390
dtype: int64

In [ ]:
myvar.loc["Jan"]

420

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

myvar1 = pd.Series(a)

print(myvar1)

x    1
y    7
z    2
dtype: int64
0    1
1    7
2    2
dtype: int64

In [ ]:
myvar["z"]

2

In [ ]:
import pandas as pd

calories = {"Jan": 420, "Feb": 380, "Mar": 390}

myvar = pd.Series(calories, index = ["x", "y", "z"])

print(myvar)

x   NaN
y   NaN
z   NaN
dtype: float64

In [ ]:
myvar = pd.Series(calories, index = ["Jan", "Feb"])

print(myvar)

Jan    420
Feb    380
dtype: int64

### Accessing elements of series

In [ ]:
import pandas as pd

import numpy as np

data = np.array(['G', 'u', 'v', 'i', 'c', 'l', 'a', 's', 'e', 's'])

ser = pd.Series(data)

print(ser[:4])

0    G
1    u
2    v
3    i
dtype: object

In [ ]:
print(ser[4:10])

4    c
5    l
6    a
7    s
8    e
9    s
dtype: object

In [ ]:
import pandas as pd

import numpy as np

data = np.array(['G', 'u', 'v', 'i', 'c', 'l', 'a', 's', 'e', 's'])

ser = pd.Series(data, index = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

print(ser[10])

G

In [ ]:
print(ser[2:6])

12    v
13    i
14    c
15    l
dtype: object

In [ ]:
print(ser[10: 12])

Series([], dtype: object)

### **Series Indexing**

In [ ]:
import pandas as pd

ser = pd.Series(['G', 'u', 'v', 'i', 'c', 'l', 'a', 's', 's', 'e', 's'])

data = ser.head(8)

data[3]

'i'

In [ ]:
print(data.loc[3: 6])

print(data.iloc[3: 6])

3    i
4    c
5    l
6    a
dtype: object
3    i
4    c
5    l
dtype: object

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar.loc["z"])

2

## **Dataframes**

### Creating DF

In [ ]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
        }

print(type(data))

myvar = pd.DataFrame(data)

print(type(myvar))

display(myvar)

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
import pandas as pd

lst = [["Guci", "classes", "for", "DS"], ["Guci", "classes", "for", "Ds"], ["I", "am", "checking"]]

df = pd.DataFrame(lst)

print(df)


display(df)

      0        1         2     3
0  Guci  classes       for    DS
1  Guci  classes       for    Ds
2     I       am  checking  None

      0        1         2     3
0  Guci  classes       for    DS
1  Guci  classes       for    Ds
2     I       am  checking  None

### **Querying DF**

In [ ]:
import pandas as pd

data = {"Name": ["Jai", "Peinci", "Gaurav", "Anuj"],
        "Age": [27, 24, 22, 32],
        "Address": ["Delhi", "Kanpur", "Allahabad", "Kannauj"],
        "Qualification": ["Msc", "MA", "MCA", "Phd"]}

df = pd.DataFrame(data)

print(df[["Qualification", "Name"]])

  Qualification    Name
0           Msc     Jai
1            MA  Peinci
2           MCA  Gaurav
3           Phd    Anuj

In [ ]:
import pandas as pd

data = {"Name": ["Jai", "Princi", "Gaurav", "Anuj"],
        "Height": [5.1, 6.2, 5.1, 5.2],
        "Qualification": ["Msc", "MA", "Msc", "Msc"]}

df = pd.DataFrame(data)

address = ["Delhi", "Bangalore", "Chennai", "Patna"]

df["Address"] = address

print(df)

     Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

In [ ]:
df.drop(["Address"], axis = 1, inplace = True)

# axis = 0 --> row

# axis = 1 --> column

In [ ]:
display(df)

     Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

In [ ]:
import pandas as pd

data = {"Name": ["Jai", "Princi", "Gaurav", "Anuj"],
        "Height": [5.1, 6.2, 5.1, 5.2],
        "Qualification": ["Msc", "MA", "Msc", "Msc"]}

df = pd.DataFrame(data)

print(df)

address = ["Delhi", "Bangalore", "Chennai", "Patna"]

df["Qualification"] = address

print(df)

     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc
     Name  Height Qualification
0     Jai     5.1         Delhi
1  Princi     6.2     Bangalore
2  Gaurav     5.1       Chennai
3    Anuj     5.2         Patna

In [ ]:
import pandas as pd

data = pd.read_excel("/content/sales_data.xlsx")

data.head()

  Order Date   Region      Rep    Item  Units  Unit Cost   Total  Shipped
0 2020-01-06     East    Jones  Pencil     95       1.99  189.05     True
1 2020-02-09  Central  Jardine  Pencil     36       4.99  179.64     True
2 2020-03-15     West  Sorvino  Pencil     56       2.99  167.44     True
3 2020-04-01     East    Jones  Binder     60       4.99  299.40    False
4 2020-05-05  Central  Jardine  Pencil     90       4.99  449.10     True

In [ ]:
import pandas as pd

data = pd.read_excel("/content/sales_data.xlsx", index_col = "Order Date")

data.head()

             Region      Rep    Item  Units  Unit Cost   Total  Shipped
Order Date
2020-01-06     East    Jones  Pencil     95       1.99  189.05     True
2020-02-09  Central  Jardine  Pencil     36       4.99  179.64     True
2020-03-15     West  Sorvino  Pencil     56       2.99  167.44     True
2020-04-01     East    Jones  Binder     60       4.99  299.40    False
2020-05-05  Central  Jardine  Pencil     90       4.99  449.10     True

In [ ]:
import pandas as pd

data = pd.read_excel("/content/sales_data.xlsx", index_col = "Order Date")

data.head()

print(type(data))

first = data.loc["2020-01-06"]

second = data.loc["2020-03-15"]

print(first, "\n\n\n", second)

<class 'pandas.core.frame.DataFrame'>
Region         East
Rep           Jones
Item         Pencil
Units            95
Unit Cost      1.99
Total        189.05
Shipped        True
Name: 2020-01-06 00:00:00, dtype: object


 Region          West
Rep          Sorvino
Item          Pencil
Units             56
Unit Cost       2.99
Total         167.44
Shipped         True
Name: 2020-03-15 00:00:00, dtype: object

### Assignment

#### **Row addition(concate) &Row deletion(drop)**

In [ ]:
import pandas as pd

import numpy as np

In [ ]:
data = pd.read_excel("/content/sales_data.xlsx")

data.head()

  Order Date   Region      Rep    Item  Units  Unit Cost   Total  Shipped
0 2020-01-06     East    Jones  Pencil     95       1.99  189.05     True
1 2020-02-09  Central  Jardine  Pencil     36       4.99  179.64     True
2 2020-03-15     West  Sorvino  Pencil     56       2.99  167.44     True
3 2020-04-01     East    Jones  Binder     60       4.99  299.40    False
4 2020-05-05  Central  Jardine  Pencil     90       4.99  449.10     True

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  12 non-null     datetime64[ns]
 1   Region      12 non-null     object
 2   Rep         12 non-null     object
 3   Item        12 non-null     object
 4   Units       12 non-null     int64
 5   Unit Cost   12 non-null     float64
 6   Total       12 non-null     float64
 7   Shipped     12 non-null     bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 812.0+ bytes

In [ ]:
data.shape

(12, 8)

In [ ]:
data = pd.read_excel("/content/sales_data.xlsx", index_col = "Order Date").iloc[0:5, :]

data.head()

             Region      Rep    Item  Units  Unit Cost   Total  Shipped
Order Date
2020-01-06     East    Jones  Pencil     95       1.99  189.05     True
2020-02-09  Central  Jardine  Pencil     36       4.99  179.64     True
2020-03-15     West  Sorvino  Pencil     56       2.99  167.44     True
2020-04-01     East    Jones  Binder     60       4.99  299.40    False
2020-05-05  Central  Jardine  Pencil     90       4.99  449.10     True

In [ ]:
data.loc["2022-01-01"] =["what", "am'I", "doing", 1, 2, 3, True]

data

,Region,Rep,Item,Units,Unit Cost,Total,Shipped
Order Date,,,,,,,
2020-01-06 00:00:00,East,Jones,Pencil,95,1.99,189.05,True
2020-02-09 00:00:00,Central,Jardine,Pencil,36,4.99,179.64,True
2020-03-15 00:00:00,West,Sorvino,Pencil,56,2.99,167.44,True
2020-04-01 00:00:00,East,Jones,Binder,60,4.99,299.40,False
2020-05-05 00:00:00,Central,Jardine,Pencil,90,4.99,449.10,True
2022-01-01,what,am'I,doing,1,2.00,3.00,True

In [ ]:
data.drop(["2022-01-01"], axis = 0, inplace = True)

In [ ]:
data

,Region,Rep,Item,Units,Unit Cost,Total,Shipped
Order Date,,,,,,,
2020-01-06 00:00:00,East,Jones,Pencil,95,1.99,189.05,True
2020-02-09 00:00:00,Central,Jardine,Pencil,36,4.99,179.64,True
2020-03-15 00:00:00,West,Sorvino,Pencil,56,2.99,167.44,True
2020-04-01 00:00:00,East,Jones,Binder,60,4.99,299.40,False
2020-05-05 00:00:00,Central,Jardine,Pencil,90,4.99,449.10,True

### **Merging data frames**

 similar function on SQL "join"

In [ ]:
import pandas as pd

data1 = {
      "name": ["Sally", "Mary", "John"],
      "age": [50, 40, 30]
      }

data2 = {
    "name": ["Sally", "Peter", "Micky"],
    "age": [77, 44, 22]
    }

df1 = pd.DataFrame(data1)

df2 = pd.DataFrame(data2)

In [ ]:
newdfa = df1.merge(df2, how = "right")

newdfa

    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [ ]:
newdfa = df1.merge(df2, how = "right", on = "name")

newdfa  # (auto renaming)

    name  age_x  age_y
0  Sally   50.0     77
1  Peter    NaN     44
2  Micky    NaN     22

In [ ]:
newdfb = df1.merge(df2, how = "left")

newdfb

    name  age
0  Sally   50
1   Mary   40
2   John   30

In [ ]:
newdfb = df1.merge(df2, how = "left", on = "name")

newdfb

    name  age_x  age_y
0  Sally     50   77.0
1   Mary     40    NaN
2   John     30    NaN

In [ ]:
newdfc = df1.merge(df2, how = "inner")

newdfc

Empty DataFrame
Columns: [name, age]
Index: []

In [ ]:
newdfc = df1.merge(df2, how = "inner", on = "name")

newdfc

    name  age_x  age_y
0  Sally     50     77

In [ ]:
newdfd = df1.merge(df2, how = "outer")

newdfd

    name  age
0  Sally   50
1   Mary   40
2   John   30
3  Sally   77
4   Mary   44
5   John   22

In [ ]:
newdfd = df1.merge(df2, how = "outer", on = "name")

newdfd

    name  age_x  age_y
0  Sally   50.0   77.0
1   Mary   40.0    NaN
2   John   30.0    NaN
3  Peter    NaN   44.0
4  Micky    NaN   22.0

In [ ]:
newdfe = df1.merge(df2, how = "cross")

newdfe      # combination of all difference row

  name_x  age_x name_y  age_y
0  Sally     50  Sally     77
1  Sally     50   Mary     44
2  Sally     50   John     22
3   Mary     40  Sally     77
4   Mary     40   Mary     44
5   Mary     40   John     22
6   John     30  Sally     77
7   John     30   Mary     44
8   John     30   John     22

In [ ]:
newdfe = df1.merge(df2, how = "cross", on = "name")

newdfe

MergeError: ignored

In [ ]:
type(newdfe)

pandas.core.frame.DataFrame

In [ ]:
import pandas as pd

data1 = {
      "name": ["Sally", "Mary", "John"],
      "age": [50, 40, 30]
      }

data2 = {
    "name": ["Sally", "Peter", "Micky"],
    "age": [77, 44, 22]
    }

df1 = pd.DataFrame(data1)

df2 = pd.DataFrame(data2, index = ["a", "b", "c"])

display(df1)

display(df2)

    name  age
0  Sally   50
1   Mary   40
2   John   30

    name  age
a  Sally   77
b  Peter   44
c  Micky   22

In [ ]:
newdfa = df1.merge(df2, how = "right", on = "name")

newdfa

    name  age_x  age_y
0  Sally   50.0     77
1  Peter    NaN     44
2  Micky    NaN     22

Extra

In [ ]:
import pandas as pd

data1 = {
      "name": ["Sally", "Mary", "John"],
      "age": [50, 40, 30]
      }

data2 = {
    "name": ["Sally", "Peter", "Micky"],
    "age": [77, 44, 22]
    }

df1 = pd.DataFrame(data1)

df2 = pd.DataFrame(data2)

display(df1)

display(df2)

    name  age
0  Sally   50
1   Mary   40
2   John   30

    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [ ]:
newdfex = df2.merge(df1, how = "right", on = "name")

newdfex

    name  age_x  age_y
0  Sally   77.0     50
1   Mary    NaN     40
2   John    NaN     30

### **Groupby operation**

.groupby()

.get_group()

In [ ]:
import pandas as pd

import numpy as np

df = pd.read_csv("https://bit.ly/3kGDuKx", na_values = "?")

df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
df_groupby_sex = df.groupby("sex")

df_groupby_sex

In [ ]:
type(df_groupby_sex)

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
df_groupby_sex.ngroups

2

In [ ]:
len(df_groupby_sex)

2

In [ ]:
df_groupby_sex.size()

sex
female    466
male      843
dtype: int64

In [ ]:
df_groupby_sex.groups   # parmeter , () function      # row below to each group

{'female': [0, 2, 4, 6, 8, 11, 12, 13, 17, 18, 21, 23, 24, 27, 28, 32, 33, 35, 36, 41, 42, 43, 44, 48, 50, 55, 57, 59, 61, 63, 65, 66, 67, 69, 72, 73, 76, 78, 79, 82, 83, 85, 88, 90, 92, 95, 97, 98, 99, 102, 103, 104, 105, 107, 108, 111, 112, 113, 116, 117, 121, 122, 124, 127, 129, 130, 131, 134, 137, 139, 141, 144, 146, 149, 153, 155, 159, 160, 161, 163, 167, 168, 169, 176, 178, 180, 181, 182, 186, 187, 188, 190, 192, 193, 195, 198, 199, 204, 207, 208, ...], 'male': [1, 3, 5, 7, 9, 10, 14, 15, 16, 19, 20, 22, 25, 26, 29, 30, 31, 34, 37, 38, 39, 40, 45, 46, 47, 49, 51, 52, 53, 54, 56, 58, 60, 62, 64, 68, 70, 71, 74, 75, 77, 80, 81, 84, 86, 87, 89, 91, 93, 94, 96, 100, 101, 106, 109, 110, 114, 115, 118, 119, 120, 123, 125, 126, 128, 132, 133, 135, 136, 138, 140, 142, 143, 145, 147, 148, 150, 151, 152, 154, 156, 157, 158, 162, 164, 165, 166, 170, 171, 172, 173, 174, 175, 177, 179, 183, 184, 185, 189, 191, ...]}

In [ ]:
df_groupby_sex.first()      # first record

,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
sex,,,,,,,,,,,,,
female,1,1,"Allen, Miss. Elisabeth Walton",29.0000,0,0,24160,211.3375,B5,S,2,52.0,"St Louis, MO"
male,1,1,"Allison, Master. Hudson Trevor",0.9167,1,2,113781,151.5500,C22 C26,S,11,135.0,"Montreal, PQ / Chesterville, ON"

In [ ]:
df_groupby_sex.last()

,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
sex,,,,,,,,,,,,,
female,3,0,"Zabour, Miss. Thamine",14.5,1,0,2665,14.4542,G6,C,C,328.0,"Wiltshire, England Niagara Falls, NY"
male,3,0,"Zimmerman, Mr. Leo",29.0,0,0,315082,7.8750,F38,S,C,304.0,"Antwerp, Belgium / Stanton, OH"

In [ ]:
df_female = df_groupby_sex.get_group("female")    # index

df_female.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"

### **Pivot table**

it is multi dimensional version of GroupBy

In [ ]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

plt.style.use("ggplot")

In [ ]:
df = pd.read_csv("https://bit.ly/3kGDuKx", na_values = "?")

df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
df.drop(["ticket", "name"], inplace = True, axis = 1)

In [ ]:
df.head(2)

,pclass,survived,sex,age,sibsp,parch,fare,cabin,embarked,boat,body,home.dest
0,1,1,female,29.0000,0,0,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,male,0.9167,1,2,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
table = pd.pivot_table(data = df, index = ["sex"])    # avg values

table   # average values (mean)

<ipython-input-76-8d42340cea9d>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  table = pd.pivot_table(data = df, index = ["sex"])

,age,body,fare,parch,pclass,sibsp,survived
sex,,,,,,,
female,28.687071,166.62500,46.198097,0.633047,2.154506,0.652361,0.727468
male,30.585233,160.39823,26.154601,0.247924,2.372479,0.413998,0.190985

In [ ]:
table = pd.pivot_table(df, index = ["sex", "pclass"])

table

<ipython-input-78-53fadf73e388>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  table = pd.pivot_table(df, index = ["sex", "pclass"])

                     age        body        fare     parch     sibsp  survived
sex    pclass
female 1       37.037594         NaN  109.412385  0.472222  0.555556  0.965278
       2       27.499191   52.000000   23.234827  0.650943  0.500000  0.886792
       3       22.185307  183.000000   15.324250  0.731481  0.791667  0.490741
male   1       41.029250  162.828571   69.888385  0.279330  0.340782  0.340782
       2       30.815401  171.233333   19.904946  0.192982  0.327485  0.146199
       3       25.962273  151.854167   12.415462  0.255578  0.470588  0.152130

In [ ]:
table = pd.pivot_table(df, index = ["sex", "pclass"], aggfunc = {"age": np.mean, "fare": np.mean})

table

                     age        fare
sex    pclass
female 1       37.037594  109.412385
       2       27.499191   23.234827
       3       22.185307   15.324250
male   1       41.029250   69.888385
       2       30.815401   19.904946
       3       25.962273   12.415462

In [ ]:
table = pd.pivot_table(data = df, index = ["sex", "pclass"], values = ["age"], aggfunc = np.mean)

table

                     age
sex    pclass
female 1       37.037594
       2       27.499191
       3       22.185307
male   1       41.029250
       2       30.815401
       3       25.962273

In [ ]:
table = pd.pivot_table(data = df, index = ["sex", "pclass"], values = ["age", "fare"], aggfunc = np.mean)

table

                     age        fare
sex    pclass
female 1       37.037594  109.412385
       2       27.499191   23.234827
       3       22.185307   15.324250
male   1       41.029250   69.888385
       2       30.815401   19.904946
       3       25.962273   12.415462

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   sex        1309 non-null   object
 3   age        1046 non-null   float64
 4   sibsp      1309 non-null   int64
 5   parch      1309 non-null   int64
 6   fare       1308 non-null   float64
 7   cabin      295 non-null    object
 8   embarked   1307 non-null   object
 9   boat       486 non-null    object
 10  body       121 non-null    float64
 11  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(5)
memory usage: 122.8+ KB

In [ ]:
table = pd.pivot_table(df, index = ["sex", "survived", "pclass"], columns = ["embarked"], values = ["age"], aggfunc = np.mean)

table

                              age
embarked                        C          Q          S
sex    survived pclass
female 0        1       43.000000        NaN  30.000000
                2             NaN        NaN  34.090909
                3       20.700000  26.692308  22.951613
       1        1       37.952381  35.000000  35.885246
                2       19.363636  30.000000  27.680209
                3       15.676471  20.500000  22.726951
male   0        1       43.216216  44.000000  43.925000
                2       30.500000  53.750000  32.606557
                3       25.722222  26.921053  26.766735
       1        1       35.538462        NaN  36.774693
                2       20.000000        NaN  16.912279
                3       20.219700  25.000000  22.855072

In [ ]:
table = pd.pivot_table(df, index = ["sex", "survived", "pclass"], columns = ["embarked"], values = ["age"], aggfunc = np.mean, fill_value = np.mean(df["age"]))


table

                              age
embarked                        C          Q          S
sex    survived pclass
female 0        1       43.000000  29.881135  30.000000
                2       29.881135  29.881135  34.090909
                3       20.700000  26.692308  22.951613
       1        1       37.952381  35.000000  35.885246
                2       19.363636  30.000000  27.680209
                3       15.676471  20.500000  22.726951
male   0        1       43.216216  44.000000  43.925000
                2       30.500000  53.750000  32.606557
                3       25.722222  26.921053  26.766735
       1        1       35.538462  29.881135  36.774693
                2       20.000000  29.881135  16.912279
                3       20.219700  25.000000  22.855072

### **Date/Time functionality**

In [ ]:
import pandas as pd

import numpy as np

In [ ]:
df = pd.DataFrame({
    "date": ["3/10/2000", "3/11/2000", "3/12/2000"],
    "value": [2, 3, 4]
})

df["date"] = pd.to_datetime(df["date"])

df

        date  value
0 2000-03-10      2
1 2000-03-11      3
2 2000-03-12      4

In [ ]:
df = pd.DataFrame({
    "date": ["3/10/2000", "3/11/2000", "3/12/2000"],
    "value": [2, 3, 4]
})

df["date"] = pd.to_datetime(df["date"], dayfirst = True)

df

        date  value
0 2000-10-03      2
1 2000-11-03      3
2 2000-12-03      4

In [ ]:
df = pd.DataFrame({
    "year": [2015, 2016],
    "month": [2, 3],
    "day": [4, 5]
})

df["date"] = pd.to_datetime(df)

df

# year, month & day are the keywords --> we can't chage it

   year  month  day       date
0  2015      2    4 2015-02-04
1  2016      3    5 2016-03-05

In [ ]:
df = pd.DataFrame({
    "month": [2, 3],
    "year": [2015, 2016],
    "day": [4, 5]
})

df["date"] = pd.to_datetime(df)

df

# year, month & day are the keywords --> we can't chage it

# default date format is yyyy-mm-dd

   month  year  day       date
0      2  2015    4 2015-02-04
1      3  2016    5 2016-03-05

In [ ]:
 import pandas as pd

 df = pd.DataFrame({
    "day": [4, 5],
    "year": [2015, 2016],
    "month": [2, 3]
})

df["date"] = pd.to_datetime(df)

df

   day  year  month       date
0    4  2015      2 2015-02-04
1    5  2016      3 2016-03-05

In [ ]:
 df = pd.DataFrame({"name": ["Tom", "Andy", "Lucas"],
                    "DoB": ["18-05-1997", "04-08-1996", "12-06-1995"]})

 df["DoB"] = pd.to_datetime(df["DoB"])

 df["year"] = df["DoB"].dt.year

 df["month"] = df["DoB"].dt.month

 df["day"] = df["DoB"].dt.day

 df

<ipython-input-5-5eae990a63c6>:4: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df["DoB"] = pd.to_datetime(df["DoB"])

    name        DoB  year  month  day
0    Tom 1997-05-18  1997      5   18
1   Andy 1996-04-08  1996      4    8
2  Lucas 1995-12-06  1995     12    6

In [ ]:
 df = pd.DataFrame({"name": ["Tom", "Andy", "Lucas"],
                    "DoB": ["18-05-1997", "04-08-1996", "12-06-1995"]})

 df["DoB"] = pd.to_datetime(df["DoB"], dayfirst = True)

 df["year"] = df["DoB"].dt.year

 df["month"] = df["DoB"].dt.month

 df["day"] = df["DoB"].dt.day

 df

    name        DoB  year  month  day
0    Tom 1997-05-18  1997      5   18
1   Andy 1996-08-04  1996      8    4
2  Lucas 1995-06-12  1995      6   12

In [ ]:
df["week_of_year"] = df["DoB"].dt.isocalendar().week    # week of the year

df["day_of_week"] = df["DoB"].dt.dayofweek      # (0 - 6) (sunday - saturday)

df["is_leap_year"] = df["DoB"].dt.is_leap_year

df

    name        DoB  year  month  day  week_of_year  day_of_week  is_leap_year
0    Tom 1997-05-18  1997      5   18            20            6         False
1   Andy 1996-04-08  1996      4    8            15            0          True
2  Lucas 1995-12-06  1995     12    6            49            2         False

In [ ]:
today = pd.to_datetime("today")

df["age"] = today.year - df["DoB"].dt.year

df

,name,DoB,year,month,day,week_of_year,day_of_week,is_leap_year,age
0,Tom,1997-05-18,1997,5,18,20,6,False,26
1,Andy,1996-04-08,1996,4,8,15,0,True,27
2,Lucas,1995-12-06,1995,12,6,49,2,False,28

In [ ]:
# change data format

import pandas as pd

df = pd.DataFrame({"date": ["3/10/2000", "3/11/2000", "3/12/2000"],
                   "value": [2, 3, 4]})

df

        date  value
0  3/10/2000      2
1  3/11/2000      3
2  3/12/2000      4

In [ ]:
df["date"] = pd.to_datetime(df["date"])

df

        date  value
0 2000-03-10      2
1 2000-03-11      3
2 2000-03-12      4

In [ ]:
df["date"] = pd.to_datetime(df["date"], dayfirst = True)

df

        date  value
0 2000-10-03      2
1 2000-11-03      3
2 2000-12-03      4

In [ ]:
df["date1"] = pd.to_datetime(df["date"], format = "%d%m%y %H:%M:%s")

df

        date  value      date1
0 2000-10-03      2 2000-10-03
1 2000-11-03      3 2000-11-03
2 2000-12-03      4 2000-12-03

In [ ]:
# get year, month and day

df = pd.DataFrame({"name": ["Tom", "Andy", "Lucas"],
                   "DoB": ["18-05-1997", "04-08-1996", "12-06-1995"]})

df["DoB"] = pd.to_datetime(df["DoB"])

df

### **Dataframe Manipulation**

In [ ]:
import pandas as pd

data = pd.DataFrame({"x1": ["x", "y", "x", "y", "x", "x"],
                     "x2": range(15, 21),
                     "x3": ["a", "b", "c", "d", "e", "f"],
                     "x4": range(20, 8, -2)})

data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
data_drop = data.drop("x3", axis = 1)

data_drop

  x1  x2  x4
0  x  15  20
1  y  16  18
2  x  17  16
3  y  18  14
4  x  19  12
5  x  20  10

In [ ]:
data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
data_drop = data.drop('x3', axis = 1, inplace = True)

data_drop   # nothing will copy

In [ ]:
data

  x1  x2  x4
0  x  15  20
1  y  16  18
2  x  17  16
3  y  18  14
4  x  19  12
5  x  20  10

In [ ]:
data = pd.DataFrame({"x1": ["x", "y", "x", "y", "x", "x"],
                     "x2": range(15, 21),
                     "x3": ["a", "b", "c", "d", "e", "f"],
                     "x4": range(20, 8, -2)})

data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
x5 = ["foo", "bar", "foo", "bar", "foo", "bar"]

print(x5)

data_add = data.assign(x5 = x5)       # copy of

data_add

['foo', 'bar', 'foo', 'bar', 'foo', 'bar']

  x1  x2 x3  x4   x5
0  x  15  a  20  foo
1  y  16  b  18  bar
2  x  17  c  16  foo
3  y  18  d  14  bar
4  x  19  e  12  foo
5  x  20  f  10  bar

In [ ]:
data_add = data.assign(check = x5)

data_add

  x1  x2 x3  x4 check
0  x  15  a  20   foo
1  y  16  b  18   bar
2  x  17  c  16   foo
3  y  18  d  14   bar
4  x  19  e  12   foo
5  x  20  f  10   bar

In [ ]:
data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
data_add["what"] = ["w", "h", "a", "t", "r", "u"]

data_add

  x1  x2 x3  x4 check what
0  x  15  a  20   foo    w
1  y  16  b  18   bar    h
2  x  17  c  16   foo    a
3  y  18  d  14   bar    t
4  x  19  e  12   foo    r
5  x  20  f  10   bar    u

In [ ]:
data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
data_2 = pd.DataFrame({"x3": ["c", "d", "e", "f", "g", "h"],
                       "y1": range(101, 107),
                       "y2": ["foo", "bar", "foo", "bar", "foo", "foo"]})

data_2

  x3   y1   y2
0  c  101  foo
1  d  102  bar
2  e  103  foo
3  f  104  bar
4  g  105  foo
5  h  106  foo

In [ ]:
data_merge = pd.merge(data, data_2, on = "x3", how = "outer")

data_merge

    x1    x2 x3    x4     y1   y2
0    x  15.0  a  20.0    NaN  NaN
1    y  16.0  b  18.0    NaN  NaN
2    x  17.0  c  16.0  101.0  foo
3    y  18.0  d  14.0  102.0  bar
4    x  19.0  e  12.0  103.0  foo
5    x  20.0  f  10.0  104.0  bar
6  NaN   NaN  g   NaN  105.0  foo
7  NaN   NaN  h   NaN  106.0  foo

In [ ]:
data_merge = pd.merge(data, data_2, on = "x3", how = "left")

data_merge

  x1  x2 x3  x4     y1   y2
0  x  15  a  20    NaN  NaN
1  y  16  b  18    NaN  NaN
2  x  17  c  16  101.0  foo
3  y  18  d  14  102.0  bar
4  x  19  e  12  103.0  foo
5  x  20  f  10  104.0  bar

In [ ]:
data_merge = pd.merge(data, data_2, on = "x3", how = "right")

data_merge

    x1    x2 x3    x4   y1   y2
0    x  17.0  c  16.0  101  foo
1    y  18.0  d  14.0  102  bar
2    x  19.0  e  12.0  103  foo
3    x  20.0  f  10.0  104  bar
4  NaN   NaN  g   NaN  105  foo
5  NaN   NaN  h   NaN  106  foo

In [ ]:
data_merge = pd.merge(data, data_2, on = "x3", how = "inner")

data_merge

  x1  x2 x3  x4   y1   y2
0  x  17  c  16  101  foo
1  y  18  d  14  102  bar
2  x  19  e  12  103  foo
3  x  20  f  10  104  bar

In [ ]:
data_merge = pd.merge(data, data_2, how = "cross")

data_merge

   x1  x2 x3_x  x4 x3_y   y1   y2
0   x  15    a  20    c  101  foo
1   x  15    a  20    d  102  bar
2   x  15    a  20    e  103  foo
3   x  15    a  20    f  104  bar
4   x  15    a  20    g  105  foo
5   x  15    a  20    h  106  foo
6   y  16    b  18    c  101  foo
7   y  16    b  18    d  102  bar
8   y  16    b  18    e  103  foo
9   y  16    b  18    f  104  bar
10  y  16    b  18    g  105  foo
11  y  16    b  18    h  106  foo
12  x  17    c  16    c  101  foo
13  x  17    c  16    d  102  bar
14  x  17    c  16    e  103  foo
15  x  17    c  16    f  104  bar
16  x  17    c  16    g  105  foo
17  x  17    c  16    h  106  foo
18  y  18    d  14    c  101  foo
19  y  18    d  14    d  102  bar
20  y  18    d  14    e  103  foo
21  y  18    d  14    f  104  bar
22  y  18    d  14    g  105  foo
23  y  18    d  14    h  106  foo
24  x  19    e  12    c  101  foo
25  x  19    e  12    d  102  bar
26  x  19    e  12    e  103  foo
27  x  19    e  12    f  104  bar
28  x  19    e  12    g  105  foo
29  x  19    e  12    h  106  foo
30  x  20    f  10    c  101  foo
31  x  20    f  10    d  102  bar
32  x  20    f  10    e  103  foo
33  x  20    f  10    f  104  bar
34  x  20    f  10    g  105  foo
35  x  20    f  10    h  106  foo

In [ ]:
data_rename = data.copy()

data.rename

<bound method DataFrame.rename of   x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10>

In [ ]:
data_rename.columns = ["col1", "col2", "col3", "col4"]

data_rename

  col1  col2 col3  col4
0    x    15    a    20
1    y    16    b    18
2    x    17    c    16
3    y    18    d    14
4    x    19    e    12
5    x    20    f    10

In [ ]:
data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

#### **Manipulate Rows of pandas DataFrame**

.sort_values()

In [ ]:
import pandas as pd

data = pd.DataFrame({"x1": ["x", "y", "x", "y", "x", "x"],
                     "x2": range(15, 21),
                     "x3": ["a", "b", "c", "d", "e", "f"],
                     "x4": range(20, 8, -2)})

data

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
data_remove = data[data["x1"] == "x"]

data_remove

  x1  x2 x3  x4
0  x  15  a  20
2  x  17  c  16
4  x  19  e  12
5  x  20  f  10

In [ ]:
new_row = ["a", "b", "c", "d"]

new_row

['a', 'b', 'c', 'd']

In [ ]:
data_new3 = data.copy()

data_new3

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

In [ ]:
data_new3.loc[6] = new_row

data_new3

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10
6  a   b  c   d

In [ ]:
data_new3.loc[9] = new_row

data_new3

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10
6  a   b  c   d
9  a   b  c   d

In [ ]:
data_new3.loc[3] = new_row

data_new3

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  a   b  c   d
4  x  19  e  12
5  x  20  f  10
6  a   b  c   d
9  a   b  c   d

In [ ]:
data_sort = data.copy()

data_sort = data_sort.sort_values("x4")

data_sort

  x1  x2 x3  x4
5  x  20  f  10
4  x  19  e  12
3  y  18  d  14
2  x  17  c  16
1  y  16  b  18
0  x  15  a  20

In [ ]:
data_sort = data.copy()

data_sort = data_sort.sort_values("x4", ascending = False)

data_sort

  x1  x2 x3  x4
0  x  15  a  20
1  y  16  b  18
2  x  17  c  16
3  y  18  d  14
4  x  19  e  12
5  x  20  f  10

#### **Replace Values in pandas**

In [ ]:
data_replace = data.copy()

data_replace["x3"] = data_replace["x3"].replace("d", "ddd")

data_replace

  x1  x2   x3  x4
0  x  15    a  20
1  y  16    b  18
2  x  17    c  16
3  y  18  ddd  14
4  x  19    e  12
5  x  20    f  10

In [ ]:
data_nan = pd.DataFrame({"x1": ["x", "x", float("NaN"), "y", float("NaN"), "y"],
                         "x2": range(24, 30),
                         "x3": ["a", "b", "c", "d", "e", "f"],
                         "x4": range(11, 5, -1)})

data_nan

    x1  x2 x3  x4
0    x  24  a  11
1    x  25  b  10
2  NaN  26  c   9
3    y  27  d   8
4  NaN  28  e   7
5    y  29  f   6

In [ ]:
data_blanks = data_nan.copy()

data_blanks = data_blanks.fillna("")

data_blanks

  x1  x2 x3  x4
0  x  24  a  11
1  x  25  b  10
2     26  c   9
3  y  27  d   8
4     28  e   7
5  y  29  f   6

In [ ]:
type(None)

NoneType

In [ ]:
data_nan = pd.DataFrame({"x1": ["x", "x", None, "y", float("NaN"), "y"],
                         "x2": range(24, 30),
                         "x3": ["a", "b", "c", "d", "e", "f"],
                         "x4": range(11, 5, -1)})

data_nan

     x1  x2 x3  x4
0     x  24  a  11
1     x  25  b  10
2  None  26  c   9
3     y  27  d   8
4   NaN  28  e   7
5     y  29  f   6

In [ ]:
data_blanks = data_nan.copy()

data_blanks = data_blanks.fillna("")

data_blanks

  x1  x2 x3  x4
0  x  24  a  11
1  x  25  b  10
2     26  c   9
3  y  27  d   8
4     28  e   7
5  y  29  f   6

In [ ]:
data_nan = pd.DataFrame({"x1": ["x", "x", "NaN", "y", "NaN", "y"],
                         "x2": range(24, 30),
                         "x3": ["a", "b", "c", "d", "e", "f"],
                         "x4": range(11, 5, -1)})

data_nan

    x1  x2 x3  x4
0    x  24  a  11
1    x  25  b  10
2  NaN  26  c   9
3    y  27  d   8
4  NaN  28  e   7
5    y  29  f   6

In [ ]:
data_blanks = data_nan.copy()

data_blanks = data_blanks.fillna("")

data_blanks

    x1  x2 x3  x4
0    x  24  a  11
1    x  25  b  10
2  NaN  26  c   9
3    y  27  d   8
4  NaN  28  e   7
5    y  29  f   6

 Series Objects are value-mutable but size-immutable objects